M48
; DRILL file KiCad 10.0.0 date 2026-04-06T11:51:39
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-04-06T11:51:39+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0728
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X3.8388Y-2.6506
X3.8388Y-2.8415
T2
X3.7195Y-2.6388
X3.7195Y-2.8533
M30
